version: "3"

services:
  client:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start -- --host=0.0.0.0
    ports:
      - 80:3000
    networks: 
      - boldarev-services
networks:
  boldarev-services:
    external:
      name: boldarev-services 